name: radial_slider
description: A radial slider widget.
version: 0.0.1
author: Amadeus <gliheng@gmail.com>
homepage: http://pyco.me

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=1.19.0 <2.0.0"
